version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo-container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    networks:
      - todo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_URL: "mongodb://admin:admin123@mongo:27017/admin"
    depends_on:
      - mongo
    networks:
      - todo-network

  # backend:
  #   build: .
  #   container_name: todo-backend
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     MONGO_URL: "mongodb://admin:admin123@mongo:27017/todo?authSource=admin"
  #   depends_on:
  #     - mongo
  #   networks:
  #     - todo-network

networks:
  todo-network:
    driver: bridge
